/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The role of the author of this message.
 */
export enum ChatCompletionResponseMessageRoleEnum {
  System = "system",
  User = "user",
  Assistant = "assistant",
}

export class ChatCompletionResponseMessage extends SpeakeasyBase {
  /**
   * The contents of the message
   */
  @SpeakeasyMetadata()
  @Expose({ name: "content" })
  content: string;

  /**
   * The role of the author of this message.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "role" })
  role: ChatCompletionResponseMessageRoleEnum;
}
