/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FunctionObject } from "./functionobject";
import { Expose, Type } from "class-transformer";

/**
 * The type of the tool. Currently, only `function` is supported.
 */
export enum ChatCompletionToolType {
    Function = "function",
}

export class ChatCompletionTool extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "function" })
    @Type(() => FunctionObject)
    function: FunctionObject;

    /**
     * The type of the tool. Currently, only `function` is supported.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: ChatCompletionToolType;
}
