/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The name and arguments of a function that should be called, as generated by the model.
 */
export class ChatCompletionRequestMessageFunctionCall extends SpeakeasyBase {
    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "arguments" })
    arguments: string;

    /**
     * The name of the function to call.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;
}

/**
 * The role of the messages author. One of `system`, `user`, `assistant`, or `function`.
 */
export enum ChatCompletionRequestMessageRole {
    System = "system",
    User = "user",
    Assistant = "assistant",
    Function = "function",
}

export class ChatCompletionRequestMessage extends SpeakeasyBase {
    /**
     * The contents of the message. `content` is required for all messages, and may be null for assistant messages with function calls.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "content" })
    content: string;

    /**
     * The name and arguments of a function that should be called, as generated by the model.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "function_call" })
    @Type(() => ChatCompletionRequestMessageFunctionCall)
    functionCall?: ChatCompletionRequestMessageFunctionCall;

    /**
     * The name of the author of this message. `name` is required if role is `function`, and it should be the name of the function whose response is in the `content`. May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The role of the messages author. One of `system`, `user`, `assistant`, or `function`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "role" })
    role: ChatCompletionRequestMessageRole;
}
