/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CreateEditRequest extends SpeakeasyBase {
    /**
     * The input text to use as a starting point for the edit.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "input" })
    input?: string;

    /**
     * The instruction that tells the model how to edit the prompt.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "instruction" })
    instruction: string;

    /**
     * ID of the model to use. You can use the `text-davinci-edit-001` or `code-davinci-edit-001` model with this endpoint.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "model" })
    model: string;

    /**
     * How many edits to generate for the input and instruction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "n" })
    n?: number;

    /**
     * completions_temperature_description
     */
    @SpeakeasyMetadata()
    @Expose({ name: "temperature" })
    temperature?: number;

    /**
     * completions_top_p_description
     */
    @SpeakeasyMetadata()
    @Expose({ name: "top_p" })
    topP?: number;
}
