/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class CreateFileRequestFile extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "multipart_form, content=true" })
    content: Uint8Array;

    @SpeakeasyMetadata({ data: "multipart_form, name=file" })
    file: string;
}

export class CreateFileRequest extends SpeakeasyBase {
    /**
     * Name of the [JSON Lines](https://jsonlines.readthedocs.io/en/latest/) file to be uploaded.
     *
     * @remarks
     *
     * If the `purpose` is set to "fine-tune", the file will be used for fine-tuning.
     *
     */
    @SpeakeasyMetadata({ data: "multipart_form, file=true" })
    file: CreateFileRequestFile;

    /**
     * The intended purpose of the uploaded documents.
     *
     * @remarks
     *
     * Use "fine-tune" for [fine-tuning](/docs/api-reference/fine-tuning). This allows us to validate the format of the uploaded file.
     *
     */
    @SpeakeasyMetadata({ data: "multipart_form, name=purpose" })
    purpose: string;
}
