/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CreateAssistantFileRequest extends SpeakeasyBase {
    /**
     * A [File](/docs/api-reference/files) ID (with `purpose="assistants"`) that the assistant should use. Useful for tools like `retrieval` and `code_interpreter` that can access files.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "file_id" })
    fileId: string;
}
