/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class File extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "multipart_form, content=true" })
    content: Uint8Array;

    @SpeakeasyMetadata({ data: "multipart_form, name=file" })
    fileName: string;
}

/**
 * The intended purpose of the uploaded file.
 *
 * @remarks
 *
 * Use "fine-tune" for [Fine-tuning](/docs/api-reference/fine-tuning) and "assistants" for [Assistants](/docs/api-reference/assistants) and [Messages](/docs/api-reference/messages). This allows us to validate the format of the uploaded file is correct for fine-tuning.
 *
 */
export enum Purpose {
    FineTune = "fine-tune",
    Assistants = "assistants",
}

export class CreateFileRequest extends SpeakeasyBase {
    /**
     * The File object (not file name) to be uploaded.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata({ data: "multipart_form, file=true" })
    file: File;

    /**
     * The intended purpose of the uploaded file.
     *
     * @remarks
     *
     * Use "fine-tune" for [Fine-tuning](/docs/api-reference/fine-tuning) and "assistants" for [Assistants](/docs/api-reference/assistants) and [Messages](/docs/api-reference/messages). This allows us to validate the format of the uploaded file is correct for fine-tuning.
     *
     */
    @SpeakeasyMetadata({ data: "multipart_form, name=purpose" })
    purpose: Purpose;
}
