/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
 *
 * @remarks
 *
 */
export class CreateAssistantRequestMetadata extends SpeakeasyBase {}

export class CreateAssistantRequest extends SpeakeasyBase {
    /**
     * The description of the assistant. The maximum length is 512 characters.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * A list of [file](/docs/api-reference/files) IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "file_ids" })
    fileIds?: string[];

    /**
     * The system instructions that the assistant uses. The maximum length is 32768 characters.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "instructions" })
    instructions?: string;

    /**
     * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => CreateAssistantRequestMetadata)
    metadata?: CreateAssistantRequestMetadata;

    /**
     * ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "model" })
    model: string;

    /**
     * The name of the assistant. The maximum length is 256 characters.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * A list of tool enabled on the assistant. There can be a maximum of 128 tools per assistant. Tools can be of types `code_interpreter`, `retrieval`, or `function`.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tools" })
    tools?: any[];
}
