/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CreateModerationRequest extends SpeakeasyBase {
  /**
   * The input text to classify
   */
  @SpeakeasyMetadata()
  @Expose({ name: "input" })
  input: any;

  /**
   * Two content moderations models are available: `text-moderation-stable` and `text-moderation-latest`.
   *
   * @remarks
   *
   * The default is `text-moderation-latest` which will be automatically upgraded over time. This ensures you are always using our most accurate model. If you use `text-moderation-stable`, we will provide advanced notice before updating the model. Accuracy of `text-moderation-stable` may be slightly lower than for `text-moderation-latest`.
   *
   */
  @SpeakeasyMetadata()
  @Expose({ name: "model" })
  model?: string;
}
