/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ChatCompletionFunctions } from "./chatcompletionfunctions";
import { ChatCompletionRequestMessage } from "./chatcompletionrequestmessage";
import { Expose, Type } from "class-transformer";

/**
 * Controls how the model responds to function calls. `none` means the model does not call a function, and responds to the end-user. `auto` means the model can pick between an end-user or calling a function.  Specifying a particular function via `{"name": "my_function"}` forces the model to call that function. `none` is the default when no functions are present. `auto` is the default if functions are present.
 */
export enum CreateChatCompletionRequestFunctionCall1 {
    None = "none",
    Auto = "auto",
}

/**
 * ID of the model to use. See the [model endpoint compatibility](/docs/models/model-endpoint-compatibility) table for details on which models work with the Chat API.
 */
export enum CreateChatCompletionRequestModel2 {
    Gpt4 = "gpt-4",
    Gpt40314 = "gpt-4-0314",
    Gpt40613 = "gpt-4-0613",
    Gpt432k = "gpt-4-32k",
    Gpt432k0314 = "gpt-4-32k-0314",
    Gpt432k0613 = "gpt-4-32k-0613",
    Gpt35Turbo = "gpt-3.5-turbo",
    Gpt35Turbo16k = "gpt-3.5-turbo-16k",
    Gpt35Turbo0301 = "gpt-3.5-turbo-0301",
    Gpt35Turbo0613 = "gpt-3.5-turbo-0613",
    Gpt35Turbo16k0613 = "gpt-3.5-turbo-16k-0613",
}

export class CreateChatCompletionRequest extends SpeakeasyBase {
    /**
     * Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
     *
     * @remarks
     *
     * [See more information about frequency and presence penalties.](/docs/guides/gpt/parameter-details)
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "frequency_penalty" })
    frequencyPenalty?: number;

    /**
     * Controls how the model responds to function calls. `none` means the model does not call a function, and responds to the end-user. `auto` means the model can pick between an end-user or calling a function.  Specifying a particular function via `{"name": "my_function"}` forces the model to call that function. `none` is the default when no functions are present. `auto` is the default if functions are present.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "function_call" })
    functionCall?: any;

    /**
     * A list of functions the model may generate JSON inputs for.
     */
    @SpeakeasyMetadata({ elemType: ChatCompletionFunctions })
    @Expose({ name: "functions" })
    @Type(() => ChatCompletionFunctions)
    functions?: ChatCompletionFunctions[];

    /**
     * Modify the likelihood of specified tokens appearing in the completion.
     *
     * @remarks
     *
     * Accepts a json object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "logit_bias" })
    logitBias?: Record<string, number>;

    /**
     * The maximum number of [tokens](/tokenizer) to generate in the chat completion.
     *
     * @remarks
     *
     * The total length of input tokens and generated tokens is limited by the model's context length. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb) for counting tokens.
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "max_tokens" })
    maxTokens?: number;

    /**
     * A list of messages comprising the conversation so far. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb).
     */
    @SpeakeasyMetadata({ elemType: ChatCompletionRequestMessage })
    @Expose({ name: "messages" })
    @Type(() => ChatCompletionRequestMessage)
    messages: ChatCompletionRequestMessage[];

    /**
     * ID of the model to use. See the [model endpoint compatibility](/docs/models/model-endpoint-compatibility) table for details on which models work with the Chat API.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "model" })
    model: any;

    /**
     * How many chat completion choices to generate for each input message.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "n" })
    n?: number;

    /**
     * Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
     *
     * @remarks
     *
     * [See more information about frequency and presence penalties.](/docs/guides/gpt/parameter-details)
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "presence_penalty" })
    presencePenalty?: number;

    /**
     * Up to 4 sequences where the API will stop generating further tokens.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "stop" })
    stop?: any;

    /**
     * If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb).
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "stream" })
    stream?: boolean;

    /**
     * What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
     *
     * @remarks
     *
     * We generally recommend altering this or `top_p` but not both.
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "temperature" })
    temperature?: number;

    /**
     * An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
     *
     * @remarks
     *
     * We generally recommend altering this or `temperature` but not both.
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "top_p" })
    topP?: number;

    /**
     * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "user" })
    user?: string;
}
