/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CompletionUsage } from "./completionusage";
import { Expose, Type } from "class-transformer";

/**
 * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
 *
 * @remarks
 * `length` if the maximum number of tokens specified in the request was reached,
 * or `content_filter` if content was omitted due to a flag from our content filters.
 *
 */
export enum CreateEditResponseFinishReason {
    Stop = "stop",
    Length = "length",
}

export class CreateEditResponseChoices extends SpeakeasyBase {
    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
     *
     * @remarks
     * `length` if the maximum number of tokens specified in the request was reached,
     * or `content_filter` if content was omitted due to a flag from our content filters.
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "finish_reason" })
    finishReason: CreateEditResponseFinishReason;

    /**
     * The index of the choice in the list of choices.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "index" })
    index: number;

    /**
     * The edited result.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "text" })
    text: string;
}

/**
 * The object type, which is always `edit`.
 */
export enum CreateEditResponseObject {
    Edit = "edit",
}

/**
 * @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export class CreateEditResponse extends SpeakeasyBase {
    /**
     * A list of edit choices. Can be more than one if `n` is greater than 1.
     */
    @SpeakeasyMetadata({ elemType: CreateEditResponseChoices })
    @Expose({ name: "choices" })
    @Type(() => CreateEditResponseChoices)
    choices: CreateEditResponseChoices[];

    /**
     * The Unix timestamp (in seconds) of when the edit was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    created: number;

    /**
     * The object type, which is always `edit`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: CreateEditResponseObject;

    /**
     * Usage statistics for the completion request.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "usage" })
    @Type(() => CompletionUsage)
    usage: CompletionUsage;
}
