/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum DeleteFileResponseObject {
    File = "file",
}

export class DeleteFileResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "deleted" })
    deleted: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: DeleteFileResponseObject;
}
