/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum DeleteAssistantFileResponseObject {
    AssistantFileDeleted = "assistant.file.deleted",
}

/**
 * Deletes the association between the assistant and the file, but does not delete the [File](/docs/api-reference/files) object itself.
 */
export class DeleteAssistantFileResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "deleted" })
    deleted: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: DeleteAssistantFileResponseObject;
}
