/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The object type, which is always "embedding".
 */
export enum EmbeddingObject {
    Embedding = "embedding",
}

/**
 * Represents an embedding vector returned by embedding endpoint.
 *
 * @remarks
 *
 */
export class Embedding extends SpeakeasyBase {
    /**
     * The embedding vector, which is a list of floats. The length of vector depends on the model as listed in the [embedding guide](/docs/guides/embeddings).
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "embedding" })
    embedding: number[];

    /**
     * The index of the embedding in the list of embeddings.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "index" })
    index: number;

    /**
     * The object type, which is always "embedding".
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: EmbeddingObject;
}
