/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class ImagesResponseData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "b64_json" })
    b64Json?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url?: string;
}

/**
 * OK
 */
export class ImagesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    created: number;

    @SpeakeasyMetadata({ elemType: ImagesResponseData })
    @Expose({ name: "data" })
    @Type(() => ImagesResponseData)
    data: ImagesResponseData[];
}
