/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Represents the url or the content of an image generated by the OpenAI API.
 */
export class Image extends SpeakeasyBase {
    /**
     * The base64-encoded JSON of the generated image, if `response_format` is `b64_json`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "b64_json" })
    b64Json?: string;

    /**
     * The URL of the generated image, if `response_format` is `url` (default).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url?: string;
}
