/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FineTuningJob } from "./finetuningjob";
import { Expose, Type } from "class-transformer";

export class ListPaginatedFineTuningJobsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: FineTuningJob })
    @Expose({ name: "data" })
    @Type(() => FineTuningJob)
    data: FineTuningJob[];

    @SpeakeasyMetadata()
    @Expose({ name: "has_more" })
    hasMore: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: string;
}
