/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MessageFileObject } from "./messagefileobject";
import { Expose, Type } from "class-transformer";

export class ListMessageFilesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: MessageFileObject })
    @Expose({ name: "data" })
    @Type(() => MessageFileObject)
    data: MessageFileObject[];

    @SpeakeasyMetadata()
    @Expose({ name: "first_id" })
    firstId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "has_more" })
    hasMore: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "last_id" })
    lastId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: string;
}
