/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FineTuneEvent } from "./finetuneevent";
import { Expose, Type } from "class-transformer";

export enum ListFineTuneEventsResponseObject {
    List = "list",
}

export class ListFineTuneEventsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: FineTuneEvent })
    @Expose({ name: "data" })
    @Type(() => FineTuneEvent)
    data: FineTuneEvent[];

    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: ListFineTuneEventsResponseObject;
}
