/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Model } from "./model";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class ListModelsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: Model })
  @Expose({ name: "data" })
  @Type(() => Model)
  data: Model[];

  @SpeakeasyMetadata()
  @Expose({ name: "object" })
  object: string;
}
