/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RunStepObject } from "./runstepobject";
import { Expose, Type } from "class-transformer";

export class ListRunStepsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: RunStepObject })
    @Expose({ name: "data" })
    @Type(() => RunStepObject)
    data: RunStepObject[];

    @SpeakeasyMetadata()
    @Expose({ name: "first_id" })
    firstId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "has_more" })
    hasMore: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "last_id" })
    lastId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: string;
}
