/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AssistantFileObject } from "./assistantfileobject";
import { Expose, Type } from "class-transformer";

export class ListAssistantFilesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: AssistantFileObject })
    @Expose({ name: "data" })
    @Type(() => AssistantFileObject)
    data: AssistantFileObject[];

    @SpeakeasyMetadata()
    @Expose({ name: "first_id" })
    firstId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "has_more" })
    hasMore: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "last_id" })
    lastId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: string;
}
