/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The reason the message is incomplete.
 */
export enum Reason {
    ContentFilter = "content_filter",
    MaxTokens = "max_tokens",
    RunCancelled = "run_cancelled",
    RunExpired = "run_expired",
    RunFailed = "run_failed",
}

/**
 * On an incomplete message, details about why the message is incomplete.
 */
export class IncompleteDetails extends SpeakeasyBase {
    /**
     * The reason the message is incomplete.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reason" })
    reason: Reason;
}

/**
 * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
 *
 * @remarks
 *
 */
export class MessageObjectMetadata extends SpeakeasyBase {}

/**
 * The object type, which is always `thread.message`.
 */
export enum MessageObjectObject {
    ThreadMessage = "thread.message",
}

/**
 * The entity that produced the message. One of `user` or `assistant`.
 */
export enum MessageObjectRole {
    User = "user",
    Assistant = "assistant",
}

/**
 * The status of the message, which can be either `in_progress`, `incomplete`, or `completed`.
 */
export enum MessageObjectStatus {
    InProgress = "in_progress",
    Incomplete = "incomplete",
    Completed = "completed",
}

/**
 * Represents a message within a [thread](/docs/api-reference/threads).
 */
export class MessageObject extends SpeakeasyBase {
    /**
     * If applicable, the ID of the [assistant](/docs/api-reference/assistants) that authored this message.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "assistant_id" })
    assistantId: string;

    /**
     * The Unix timestamp (in seconds) for when the message was completed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "completed_at" })
    completedAt: number;

    /**
     * The content of the message in array of text and/or images.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "content" })
    content: any[];

    /**
     * The Unix timestamp (in seconds) for when the message was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: number;

    /**
     * A list of [file](/docs/api-reference/files) IDs that the assistant should use. Useful for tools like retrieval and code_interpreter that can access files. A maximum of 10 files can be attached to a message.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "file_ids" })
    fileIds: string[];

    /**
     * The identifier, which can be referenced in API endpoints.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The Unix timestamp (in seconds) for when the message was marked as incomplete.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "incomplete_at" })
    incompleteAt: number;

    /**
     * On an incomplete message, details about why the message is incomplete.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "incomplete_details" })
    @Type(() => IncompleteDetails)
    incompleteDetails: IncompleteDetails;

    /**
     * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => MessageObjectMetadata)
    metadata: MessageObjectMetadata;

    /**
     * The object type, which is always `thread.message`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: MessageObjectObject;

    /**
     * The entity that produced the message. One of `user` or `assistant`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "role" })
    role: MessageObjectRole;

    /**
     * The ID of the [run](/docs/api-reference/runs) associated with the creation of this message. Value is `null` when messages are created manually using the create message or create thread endpoints.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "run_id" })
    runId: string;

    /**
     * The status of the message, which can be either `in_progress`, `incomplete`, or `completed`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: MessageObjectStatus;

    /**
     * The [thread](/docs/api-reference/threads) ID that this message belongs to.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "thread_id" })
    threadId: string;
}
