/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
 *
 * @remarks
 *
 */
export class MessageObjectMetadata extends SpeakeasyBase {}

/**
 * The object type, which is always `thread.message`.
 */
export enum MessageObjectObject {
    ThreadMessage = "thread.message",
}

/**
 * The entity that produced the message. One of `user` or `assistant`.
 */
export enum MessageObjectRole {
    User = "user",
    Assistant = "assistant",
}

/**
 * Represents a message within a [thread](/docs/api-reference/threads).
 */
export class MessageObject extends SpeakeasyBase {
    /**
     * If applicable, the ID of the [assistant](/docs/api-reference/assistants) that authored this message.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "assistant_id" })
    assistantId: string;

    /**
     * The content of the message in array of text and/or images.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "content" })
    content: any[];

    /**
     * The Unix timestamp (in seconds) for when the message was created.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt: number;

    /**
     * A list of [file](/docs/api-reference/files) IDs that the assistant should use. Useful for tools like retrieval and code_interpreter that can access files. A maximum of 10 files can be attached to a message.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "file_ids" })
    fileIds: string[];

    /**
     * The identifier, which can be referenced in API endpoints.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => MessageObjectMetadata)
    metadata: MessageObjectMetadata;

    /**
     * The object type, which is always `thread.message`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "object" })
    object: MessageObjectObject;

    /**
     * The entity that produced the message. One of `user` or `assistant`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "role" })
    role: MessageObjectRole;

    /**
     * If applicable, the ID of the [run](/docs/api-reference/runs) associated with the authoring of this message.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "run_id" })
    runId: string;

    /**
     * The [thread](/docs/api-reference/threads) ID that this message belongs to.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "thread_id" })
    threadId: string;
}
