/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Usage statistics related to the run. This value will be `null` if the run is not in a terminal state (i.e. `in_progress`, `queued`, etc.).
 */
export class RunCompletionUsage extends SpeakeasyBase {
    /**
     * Number of completion tokens used over the course of the run.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "completion_tokens" })
    completionTokens: number;

    /**
     * Number of prompt tokens used over the course of the run.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "prompt_tokens" })
    promptTokens: number;

    /**
     * Total number of tokens used (prompt + completion).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "total_tokens" })
    totalTokens: number;
}
