/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class GetMessageFileRequest extends SpeakeasyBase {
    /**
     * The ID of the file being retrieved.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=file_id" })
    fileId: string;

    /**
     * The ID of the message the file belongs to.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=message_id" })
    messageId: string;

    /**
     * The ID of the thread to which the message and File belong.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=thread_id" })
    threadId: string;
}

export class GetMessageFileResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    messageFileObject?: shared.MessageFileObject;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
