/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class GetMessageRequest extends SpeakeasyBase {
    /**
     * The ID of the message to retrieve.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=message_id" })
    messageId: string;

    /**
     * The ID of the [thread](/docs/api-reference/threads) to which this message belongs.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=thread_id" })
    threadId: string;
}

export class GetMessageResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    messageObject?: shared.MessageObject;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
