/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ListFineTuningEventsRequest extends SpeakeasyBase {
    /**
     * Identifier for the last event from the previous pagination request.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=after" })
    after?: string;

    /**
     * The ID of the fine-tuning job to get events for.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=fine_tuning_job_id" })
    fineTuningJobId: string;

    /**
     * Number of events to retrieve.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=limit" })
    limit?: number;
}

export class ListFineTuningEventsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    listFineTuningJobEventsResponse?: shared.ListFineTuningJobEventsResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
