/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ListFineTuneEventsRequest extends SpeakeasyBase {
    /**
     * The ID of the fine-tune job to get events for.
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=fine_tune_id" })
    fineTuneId: string;

    /**
     * Whether to stream events for the fine-tune job. If set to true,
     *
     * @remarks
     * events will be sent as data-only
     * [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format)
     * as they become available. The stream will terminate with a
     * `data: [DONE]` message when the job is finished (succeeded, cancelled,
     * or failed).
     *
     * If set to false, only events generated so far will be returned.
     *
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=stream" })
    stream?: boolean;
}

export class ListFineTuneEventsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    listFineTuneEventsResponse?: shared.ListFineTuneEventsResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
