/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RetrieveFineTuneRequest extends SpeakeasyBase {
    /**
     * The ID of the fine-tune job
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=fine_tune_id" })
    fineTuneId: string;
}

export class RetrieveFineTuneResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    fineTune?: shared.FineTune;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
