/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class RetrieveFineTuningJobRequest extends SpeakeasyBase {
    /**
     * The ID of the fine-tuning job
     *
     * @remarks
     *
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=fine_tuning_job_id" })
    fineTuningJobId: string;
}

export class RetrieveFineTuningJobResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    fineTuningJob?: shared.FineTuningJob;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
