name: Generate

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force the generation of the SDKs"
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *


jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v7
    with:
      speakeasy_version: latest
      openapi_doc_location: https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml
      languages: |-
        - typescript: ./
       
      mode: pr
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
